apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reverse-proxy.fullname" . }}-config
  labels:
    app: {{ include "reverse-proxy.name" . }}
data:
  Caddyfile: |
    # Redirect HTTP to HTTPS
    http:// {
        redir https://{host}{uri}
    }

    # HTTPS site configuration
    {{ .Values.reverseProxy.url }} {
        tls {{ .Values.reverseProxy.email }}  # Email used for Let's Encrypt registration

        handle / {
            respond "Under Construction" 200
        }

        handle_path /api/python-rest* {
            reverse_proxy python-rest-api-dev:9001
        }

        handle /wiki {
            redir {{ .Values.reverseProxy.wikiUrl }}
        }
    }