apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reverse-proxy.fullname" . }}
  labels:
    app: {{ include "reverse-proxy.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "reverse-proxy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "reverse-proxy.name" . }}
      annotations:
        checksum/configmap-caddyfile: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: caddy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddy-config
          configMap:
            name: {{ include "reverse-proxy.fullname" . }}-config
