apiVersion: v1
kind: Service
metadata:
  name: {{ include "reverse-proxy.fullname" . }}
  labels:
    app: {{ include "reverse-proxy.name" . }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.service.azureDnsLabelName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "reverse-proxy.name" . }}
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
