# Default values for reverse-proxy Helm chart

replicaCount: 1
image:
  repository: caddy
  tag: 2.7.6
  pullPolicy: IfNotPresent

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: null

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: yourdomain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - hosts:
  #      - yourdomain.com
  #    secretName: yourdomain-tls

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP

serviceAccount:
  create: false
  name: ""
  automount: true
  annotations: {}

reverseProxy:
  # The URL for the FQDN (Fully Qualified Domain Name) of the reverse proxy. This will be used to ensure proper SSL/TLS configuration.
  url: "https://your-service-url:443"
  # The e-mail address used for Let's Encrypt registration for the creation of SSL/TLS certificates. This should be a valid email address to receive notifications about certificate renewals and issues.
  email: "your-email@your-provider.com"
  # The URL for the Wiki application. When an user accesses the /wiki path, they will be redirected to this URL.
  wikiUrl: "https://your-wiki-page"